name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.x]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install essentials
        run: pip install -U --user setuptools twine wheel

      - name: Build
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload --skip-existing dist/*

      - name: Release
        uses: softprops/action-gh-release@v1
